"""initial schema with trade_hash

Revision ID: c4838cd01bbd
Revises: 
Create Date: 2026-09-22 12:30:28.075608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4838cd01bbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_time_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_time_intervals_id'), 'custom_time_intervals', ['id'], unique=False)
    op.create_table('personal_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_accounts_id'), 'personal_accounts', ['id'], unique=False)
    op.create_table('prop_firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_profit_share', sa.Float(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_firms_id'), 'prop_firms', ['id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_table('symbol_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_symbol', sa.String(), nullable=False),
    sa.Column('canonical_symbol', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_symbol')
    )
    op.create_index(op.f('ix_symbol_mappings_id'), 'symbol_mappings', ['id'], unique=False)
    op.create_table('time_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_points_id'), 'time_points', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('calendar', sa.String(), nullable=True),
    sa.Column('default_risk_percent', sa.Integer(), nullable=True),
    sa.Column('default_profit_share', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('prop_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_firm_id', sa.Integer(), nullable=False),
    sa.Column('account_label', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prop_firm_id'], ['prop_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_accounts_id'), 'prop_accounts', ['id'], unique=False)
    op.create_table('prop_firm_default_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_firm_id', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('STAGE_1', 'STAGE_2', 'FUNDED_REAL', name='stagetype'), nullable=False),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('max_daily_dd', sa.Float(), nullable=True),
    sa.Column('max_total_dd', sa.Float(), nullable=True),
    sa.Column('min_trading_days', sa.Integer(), nullable=True),
    sa.Column('profit_share_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prop_firm_id'], ['prop_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_firm_default_rules_id'), 'prop_firm_default_rules', ['id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('rules_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RESEARCH', 'BACKTEST', 'OPTIMIZATION', 'FORWARD', 'APPROVED', 'LIVE', 'REVIEW', 'DEPRECATED', 'ARCHIVED', 'REJECTED', name='strategystatus'), nullable=True),
    sa.Column('forked_from_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forked_from_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_id'), 'strategy_versions', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('net_r', sa.Float(), nullable=True),
    sa.Column('max_dd', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('expectancy_r', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('largest_win', sa.Float(), nullable=True),
    sa.Column('largest_loss', sa.Float(), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('consistency_analysis', sa.JSON(), nullable=True),
    sa.Column('session_analysis', sa.JSON(), nullable=True),
    sa.Column('weekday_analysis', sa.JSON(), nullable=True),
    sa.Column('hour_analysis', sa.JSON(), nullable=True),
    sa.Column('custom_time_analysis', sa.JSON(), nullable=True),
    sa.Column('time_point_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('TRADE_PNL', 'PROP_PAYOUT', 'DEPOSIT', 'WITHDRAWAL', 'CHALLENGE_FEE', 'EXPENSE', 'MANUAL_ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('personal_account_id', sa.Integer(), nullable=True),
    sa.Column('prop_account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personal_account_id'], ['personal_accounts.id'], ),
    sa.ForeignKeyConstraint(['prop_account_id'], ['prop_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_id'), 'ledger_transactions', ['id'], unique=False)
    op.create_table('prop_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_account_id', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('cost_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_refunded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prop_account_id'], ['prop_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_costs_id'), 'prop_costs', ['id'], unique=False)
    op.create_table('prop_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_account_id', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('STAGE_1', 'STAGE_2', 'FUNDED_REAL', name='stagetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PASSED', 'FAILED', 'CLOSED', name='stagestatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('max_daily_dd', sa.Float(), nullable=True),
    sa.Column('max_total_dd', sa.Float(), nullable=True),
    sa.Column('min_trading_days', sa.Integer(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('final_balance', sa.Float(), nullable=True),
    sa.Column('profit_share_percentage', sa.Float(), nullable=True),
    sa.Column('total_withdrawn', sa.Float(), nullable=True),
    sa.Column('current_profit', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Enum('MAX_DAILY_DD_EXCEEDED', 'MAX_TOTAL_DD_EXCEEDED', 'PROFIT_TARGET_NOT_MET', 'MIN_TRADING_DAYS_NOT_MET', 'RULE_VIOLATION', 'MANUAL', 'OTHER', name='failurereason'), nullable=True),
    sa.Column('failure_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prop_account_id'], ['prop_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_stages_id'), 'prop_stages', ['id'], unique=False)
    op.create_table('prop_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_stage_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prop_stage_id'], ['prop_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_alerts_id'), 'prop_alerts', ['id'], unique=False)
    op.create_table('prop_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_stage_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('withdrawal_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prop_stage_id'], ['prop_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_withdrawals_id'), 'prop_withdrawals', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('prop_stage_id', sa.Integer(), nullable=True),
    sa.Column('personal_account_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('entry_sequence', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MT4_IMPORT', 'SOFT4X_IMPORT', 'MANUAL', name='tradesource'), nullable=False),
    sa.Column('test_type', sa.Enum('BACKTEST', 'FORWARD', 'REAL', name='testtype'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trade_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['personal_account_id'], ['personal_accounts.id'], ),
    sa.ForeignKeyConstraint(['prop_stage_id'], ['prop_stages.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_trade_hash'), 'trades', ['trade_hash'], unique=False)
    op.create_table('journal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('setup_quality', sa.Integer(), nullable=True),
    sa.Column('execution_quality', sa.Integer(), nullable=True),
    sa.Column('rule_violations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_reviews_id'), 'journal_reviews', ['id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['journal_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_journal_reviews_id'), table_name='journal_reviews')
    op.drop_table('journal_reviews')
    op.drop_index(op.f('ix_trades_trade_hash'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_prop_withdrawals_id'), table_name='prop_withdrawals')
    op.drop_table('prop_withdrawals')
    op.drop_index(op.f('ix_prop_alerts_id'), table_name='prop_alerts')
    op.drop_table('prop_alerts')
    op.drop_index(op.f('ix_prop_stages_id'), table_name='prop_stages')
    op.drop_table('prop_stages')
    op.drop_index(op.f('ix_prop_costs_id'), table_name='prop_costs')
    op.drop_table('prop_costs')
    op.drop_index(op.f('ix_ledger_transactions_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_strategy_versions_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_prop_firm_default_rules_id'), table_name='prop_firm_default_rules')
    op.drop_table('prop_firm_default_rules')
    op.drop_index(op.f('ix_prop_accounts_id'), table_name='prop_accounts')
    op.drop_table('prop_accounts')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_time_points_id'), table_name='time_points')
    op.drop_table('time_points')
    op.drop_index(op.f('ix_symbol_mappings_id'), table_name='symbol_mappings')
    op.drop_table('symbol_mappings')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_prop_firms_id'), table_name='prop_firms')
    op.drop_table('prop_firms')
    op.drop_index(op.f('ix_personal_accounts_id'), table_name='personal_accounts')
    op.drop_table('personal_accounts')
    op.drop_index(op.f('ix_custom_time_intervals_id'), table_name='custom_time_intervals')
    op.drop_table('custom_time_intervals')
    # ### end Alembic commands ###
